### ISSUE TITLE
Parameter setting

### ISSUE THREAD

**Issue by fzb408** [littlexinyi/MGCC#1]
Thank you for your great work! How to set parameters in options.py(like IDloss) to reproduce the results in the paper？

**Comment by littlexinyi** [comment]
Thanks for following us. The parameters for different datasets are setted in experiments/CUHK-PEDES/train.sh or experiments/CUHK-PEDES/test.sh.

**Comment by fzb408** [comment]
I reproduced the paper according to the experimental setting in train.sh, but it was lower by nearly 3% R@1，did I miss something？
