### ISSUE TITLE
CUHK-PEDES.json

### ISSUE THREAD

**Issue by zqxie77** [littlexinyi/MGCC#3]
在复现您项目的时候  我找不到这个CUHK-PEDES.json文件 请问可以提供吗

**Comment by littlexinyi** [comment]
Thanks for your attention to our work. Due to copyright restrictions, we cannot provide the CUHK-PEDES.json file of the CUHK-PEDES dataset. You can find it in this [link](https://github.com/ShuangLI59/Person-Search-with-Natural-Language-Description) or contact the original author directly by email.

**Comment by zqxie77** [comment]
里面只有
![image](https://github.com/user-attachments/assets/3460724e-7f07-4a41-9835-480d5645d979)

**Comment by zqxie77** [comment]
但是里面只有[cid:e46aefac-8700-4c88-aaef-500c039554dc]

________________________________

**Comment by littlexinyi** [comment]
reid_raw.json就是CUHK-PEDES.json



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "littlexinyi/MGCC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月26日(星期二) 下午5:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [littlexinyi/MGCC] CUHK-PEDES.json (Issue #3)





 但是里面只有[cid:e46aefac-8700-4c88-aaef-500c039554dc] 
 
 ________________________________
